import type { Metadata } from "next";
import { Ubuntu } from 'next/font/google';
import "./globals.css";
import Navbar03Page from "@/components/navbar-03/navbar-03";
import Footer04Page from "@/components/footer-04/footer-04";

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: "300"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ubuntu.variable}>
        <Navbar03Page/>
        {children}
        <Footer04Page />
      </body>
    </html>
  );
}
